-- down migration: initial schema
DROP TABLE IF EXISTS course_number_alias CASCADE;
DROP TABLE IF EXISTS event_log CASCADE;
DROP TABLE IF EXISTS actions CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS course_evaluation_map CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS courses CASCADE;

DROP TYPE IF EXISTS status;

DROP TABLE IF EXISTS current_semester CASCADE;